version: '3'

services:
  shop:
    image: dockware/play:latest
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
    volumes:
      - "db_data:/var/lib/mysql"
      - "./TeamPlugin:/var/www/html/custom/plugins/TeamPlugin"
    environment:
      - "XDEBUG_ENABLED=1"

volumes:
  db_data:
    driver: local
